spring:
  profiles:
    active: dev
---
server:
  port: 9003
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  profiles: dev